application: strikegrouptest
version: 2
runtime: python27
api_version: 1
threadsafe: yes

#builtins:
#- datastore_admin: on
#- appstats: off

#inbound_services:
#- warmup

#default_expiration: "5d"

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/docs/robots.txt
  upload: static/docs/robots.txt

- url: /sitemap.xml
  static_files: static/docs/sitemap.xml
  upload: static/docs/sitemap.xml

- url: /(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /(.*\.js)
  static_files: static/scripts/\1
  upload: static/scripts/(.*\.js)

- url: /(.*\.css)
  static_files: static/stylesheets/\1
  upload: static/stylesheets/(.*\.css)

- url: /(.*\.(mp3|mp4|ogv|ogg|webm|swf))
  static_files: static/media/\1
  upload: static/media/(.*\.(mp3|mp4|ogv|ogg|webm|swf))

#- url: /admin
# script: app.main.application
#  login: admin

- url: /.*
  script: app.main.application

- url: /usmc/.*
  script: app.main.application

libraries:
- name: django
  version: "1.2"
- name: jinja2
  version: latest
- name: yaml
  version: latest