application: strikegrouptest
version: 3
runtime: python27
api_version: 1
threadsafe: yes

#builtins:
#- datastore_admin: on
#- appstats: off

#inbound_services:
#- warmup

#default_expiration: "5d"

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/docs/robots.txt
  upload: static/docs/robots.txt

- url: /sitemap.xml
  static_files: static/docs/sitemap.xml
  upload: static/docs/sitemap.xml

- url: /(.*\.(pdf|xml|atom))
  static_files: static/docs/\1
  upload: static/docs/(.*\.(pdf|xml|atom))

- url: /newsletter/(.*\.(pdf))
  static_files: static/docs/newsletter/\1
  upload: static/docs/newsletter/(.*\.(pdf))

- url: /(.*\.html)
  static_files: static/html/\1
  upload: static/html/(.*\.html)

- url: /(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /(.*\.js)
  static_files: static/scripts/\1
  upload: static/scripts/(.*\.js)

- url: /(.*\.css)
  static_files: static/stylesheets/\1
  upload: static/stylesheets/(.*\.css)

- url: /(.*\.(mp3|mp4|ogv|ogg|webm|swf))
  static_files: static/media/\1
  upload: static/media/(.*\.(mp3|mp4|ogv|ogg|webm|swf))


- url: /.*
  script: app.main.application

libraries:
- name: jinja2
  version: latest
- name: yaml
  version: latest